#theme : moon
theme-override : git-pitch/assets/css/PITCHME.css
logo : git-pitch/assets/images/logo.png

#GitPitch supports six distinct layouts. The supported layouts are named center, center-left, center-right, top, top-left, and top-right respectively.
layout : right

#transition : convex
#transition : concave
#transition : default
transition : fade
#transition : none
#transition : slide
#transition : zoom
